# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

jobs:
    unit-test:
        working_directory: ~/aryashreep.github.io
        # The primary container is an instance of the first list image listed. Your test commands run in this container.
        docker:
            - image: circleci/node:8
              environment:
                  CHROME_BIN: "/usr/bin/google-chrome"
            # Specify service dependencies here if necessary
            # CircleCI maintains a library of pre-built images
            # documented at https://circleci.com/docs/2.0/circleci-images/
            # - image: circleci/mongo:3.4.4
        steps:
            - checkout
            - run:
                name: Install node_modules with npm
                command: npm install
            - save_cache:
                key: dependency-cache-{{ checksum "package.json" }}
                paths:
                    - ./node_modules
            - run:
                name: Install aryashreep.github.io
                command: |
                  sudo npm install -g @angular/cli@latest
                  sudo npm install -g angular-cli-ghpages
                  sudo npm install typescript@'>=2.4.2 <2.6.0'
                  sudo touch test-results.xml
                  sudo chmod 777 test-results.xml

            - run:
                name: Run unit tests with karma
                command: ng test --watch false -cc

            - run:
                name: Run end to end test
                command: ng e2e               
                
            - store_test_results:
                path: test-results.xml

    build-job:
        working_directory: ~/aryashreep.github.io
        # The primary container is an instance of the first list image listed. Your test commands run in this container.
        docker:
            - image: circleci/node:7.10.0-browsers

        steps:
            - checkout
            - run:
                name: Install node_modules with npm
                command: npm install
            - save_cache:
                key: dependency-cache-{{ checksum "package.json" }}
                paths:
                    - ./node_modules
            - run:
                name: Install aryashreep.github.io
                command: |
                  sudo npm install -g @angular/cli@latest
                  sudo npm install typescript@'>=2.4.2 <2.6.0'
                  sudo mkdir dist
                  sudo chmod 777 dist

            - run:
                name: Run build
                command: ng build --prod

    deploy-job:
        working_directory: ~/aryashreep.github.io
        # The primary container is an instance of the first list image listed. Your test commands run in this container.
        docker:
            - image: circleci/node:7.10.0-browsers

        steps:
            - checkout
            - run:
                name: Install node_modules with npm
                command: npm install
            - save_cache:
                key: dependency-cache-{{ checksum "package.json" }}
                paths:
                    - ./node_modules
            - run:
                name: Install aryashreep.github.io
                command: |
                  sudo npm install -g @angular/cli@latest
                  sudo npm install -g angular-cli-ghpages
                  sudo npm install typescript@'>=2.4.2 <2.6.0'
                  sudo mkdir dist
                  sudo chmod 777 dist

            - run:
                name: Deployment the build
                command: angular-cli-ghpages --no-silent --branch=master

workflows:
  version: 2
  default-workflow:
    jobs:
      - unit-test
      - build-job
      - deploy-job
